// ==========================================
// Mock Data for Demo Mode
// ==========================================
import type {
  Profile,
  Trip,
  Match,
  ChatRoom,
  Message,
  Notification,
  Post,
  TravelRecommendation,
  LocalGuide,
  InsurancePlan,
  PartnerDeal,
  CommunityBoard,
} from '@/types';

// Mock Users/Profiles
export const mockProfiles: Profile[] = [
  {
    id: '1',
    user_id: 'user-1',
    full_name: 'Priya Sharma',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    bio: 'Adventure seeker & mountain lover. Always looking for the next summit to conquer!',
    gender: 'female',
    date_of_birth: '1995-03-15',
    interests: ['hiking', 'photography', 'yoga', 'local cuisine'],
    travel_style: ['adventure', 'backpacking', 'nature'],
    languages: ['English', 'Hindi', 'French'],
    location: 'Mumbai, India',
    safety_badge: 'gold',
    is_verified: true,
    is_premium: true,
    rating_avg: 4.8,
    total_trips: 12,
    trust_score: 92,
    kyc_status: 'approved',
    onboarding_complete: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: '2',
    user_id: 'user-2',
    full_name: 'Rahul Verma',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul',
    bio: 'Food explorer and culture enthusiast. Traveled to 20+ countries!',
    gender: 'male',
    date_of_birth: '1992-07-22',
    interests: ['food tours', 'museums', 'history', 'photography'],
    travel_style: ['cultural', 'food_explorer', 'photography'],
    languages: ['English', 'Hindi', 'Spanish'],
    location: 'Delhi, India',
    safety_badge: 'platinum',
    is_verified: true,
    is_premium: true,
    rating_avg: 4.9,
    total_trips: 28,
    trust_score: 98,
    kyc_status: 'approved',
    onboarding_complete: true,
    created_at: '2023-06-10T10:00:00Z',
    updated_at: '2024-11-20T10:00:00Z',
  },
  {
    id: '3',
    user_id: 'user-3',
    full_name: 'Ananya Patel',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ananya',
    bio: 'Solo traveler by heart. Love meeting new people and sharing stories.',
    gender: 'female',
    date_of_birth: '1998-11-05',
    interests: ['backpacking', 'hostels', 'street food', 'music'],
    travel_style: ['budget', 'solo', 'backpacking'],
    languages: ['English', 'Hindi', 'German'],
    location: 'Bangalore, India',
    safety_badge: 'silver',
    is_verified: true,
    is_premium: false,
    rating_avg: 4.6,
    total_trips: 8,
    trust_score: 78,
    kyc_status: 'approved',
    onboarding_complete: true,
    created_at: '2024-03-20T10:00:00Z',
    updated_at: '2024-10-15T10:00:00Z',
  },
  {
    id: '4',
    user_id: 'user-4',
    full_name: 'Vikram Singh',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram',
    bio: 'Beach lover and water sports enthusiast. Scuba certified diver.',
    gender: 'male',
    date_of_birth: '1990-05-18',
    interests: ['beaches', 'scuba diving', 'surfing', 'nightlife'],
    travel_style: ['adventure', 'relaxation', 'luxury'],
    languages: ['English', 'Hindi'],
    location: 'Goa, India',
    safety_badge: 'gold',
    is_verified: true,
    is_premium: true,
    rating_avg: 4.7,
    total_trips: 15,
    trust_score: 88,
    kyc_status: 'approved',
    onboarding_complete: true,
    created_at: '2023-09-05T10:00:00Z',
    updated_at: '2024-11-01T10:00:00Z',
  },
  {
    id: '5',
    user_id: 'user-5',
    full_name: 'Meera Krishnan',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Meera',
    bio: 'Yoga instructor who loves spiritual retreats and peaceful destinations.',
    gender: 'female',
    date_of_birth: '1993-09-28',
    interests: ['yoga', 'meditation', 'temples', 'wellness'],
    travel_style: ['relaxation', 'cultural', 'nature'],
    languages: ['English', 'Hindi', 'Tamil'],
    location: 'Chennai, India',
    safety_badge: 'silver',
    is_verified: true,
    is_premium: false,
    rating_avg: 4.5,
    total_trips: 6,
    trust_score: 72,
    kyc_status: 'approved',
    onboarding_complete: true,
    created_at: '2024-02-14T10:00:00Z',
    updated_at: '2024-09-20T10:00:00Z',
  },
];

// Mock Trips
export const mockTrips: Trip[] = [
  {
    id: 'trip-1',
    creator_id: '2',
    title: 'Ladakh Adventure - Leh to Pangong',
    destination: 'Leh-Ladakh, India',
    destination_coords: { lat: 34.1526, lng: 77.5771 },
    start_date: '2025-01-15',
    end_date: '2025-01-25',
    budget_min: 25000,
    budget_max: 40000,
    budget_currency: 'INR',
    travel_style: ['adventure', 'photography', 'nature'],
    gender_preference: 'any',
    age_range_min: 22,
    age_range_max: 40,
    max_participants: 4,
    current_participants: 1,
    interests: ['hiking', 'photography', 'camping', 'mountains'],
    description: 'An epic 10-day journey through the breathtaking landscapes of Ladakh. We will cover Leh, Nubra Valley, Pangong Lake, and hidden monasteries.',
    itinerary: [
      { day: 1, title: 'Arrival in Leh', description: 'Acclimatization day' },
      { day: 2, title: 'Leh Exploration', description: 'Visit Shanti Stupa, Leh Palace' },
      { day: 3, title: 'Khardung La', description: 'World\'s highest motorable road' },
    ],
    status: 'open',
    is_group_trip: true,
    created_at: '2024-12-01T10:00:00Z',
    updated_at: '2024-12-05T10:00:00Z',
    creator: mockProfiles[1],
  },
  {
    id: 'trip-2',
    creator_id: '1',
    title: 'Goa Beach Retreat',
    destination: 'Goa, India',
    destination_coords: { lat: 15.2993, lng: 74.124 },
    start_date: '2025-02-01',
    end_date: '2025-02-07',
    budget_min: 15000,
    budget_max: 25000,
    budget_currency: 'INR',
    travel_style: ['relaxation', 'adventure'],
    gender_preference: 'female',
    age_range_min: 25,
    age_range_max: 35,
    max_participants: 3,
    current_participants: 1,
    interests: ['beaches', 'yoga', 'water sports', 'nightlife'],
    description: 'A week-long beach vacation in South Goa. Looking for like-minded women travelers for a fun and safe trip.',
    status: 'open',
    is_group_trip: false,
    created_at: '2024-12-03T10:00:00Z',
    updated_at: '2024-12-05T10:00:00Z',
    creator: mockProfiles[0],
  },
  {
    id: 'trip-3',
    creator_id: '3',
    title: 'Budget Backpacking - Rishikesh',
    destination: 'Rishikesh, India',
    destination_coords: { lat: 30.0869, lng: 78.2676 },
    start_date: '2025-01-20',
    end_date: '2025-01-26',
    budget_min: 8000,
    budget_max: 12000,
    budget_currency: 'INR',
    travel_style: ['budget', 'adventure', 'backpacking'],
    gender_preference: 'any',
    age_range_min: 20,
    age_range_max: 30,
    max_participants: 5,
    current_participants: 2,
    interests: ['rafting', 'yoga', 'camping', 'trekking'],
    description: 'Budget-friendly adventure trip! River rafting, camping, cafe hopping, and good vibes only.',
    status: 'open',
    is_group_trip: true,
    created_at: '2024-12-02T10:00:00Z',
    updated_at: '2024-12-04T10:00:00Z',
    creator: mockProfiles[2],
  },
  {
    id: 'trip-4',
    creator_id: '4',
    title: 'Andaman Islands Scuba Adventure',
    destination: 'Andaman Islands, India',
    destination_coords: { lat: 11.7401, lng: 92.6586 },
    start_date: '2025-03-10',
    end_date: '2025-03-18',
    budget_min: 45000,
    budget_max: 60000,
    budget_currency: 'INR',
    travel_style: ['adventure', 'luxury'],
    gender_preference: 'any',
    age_range_min: 25,
    age_range_max: 45,
    max_participants: 4,
    current_participants: 1,
    interests: ['scuba diving', 'snorkeling', 'beaches', 'island hopping'],
    description: 'Certified divers preferred! We will explore Havelock, Neil Island, and do multiple dives at some of the best sites.',
    status: 'open',
    is_group_trip: true,
    created_at: '2024-12-04T10:00:00Z',
    updated_at: '2024-12-05T10:00:00Z',
    creator: mockProfiles[3],
  },
  {
    id: 'trip-5',
    creator_id: '5',
    title: 'Kerala Ayurveda & Yoga Retreat',
    destination: 'Kerala, India',
    destination_coords: { lat: 10.8505, lng: 76.2711 },
    start_date: '2025-02-15',
    end_date: '2025-02-22',
    budget_min: 30000,
    budget_max: 45000,
    budget_currency: 'INR',
    travel_style: ['relaxation', 'cultural'],
    gender_preference: 'female',
    age_range_min: 28,
    age_range_max: 50,
    max_participants: 6,
    current_participants: 1,
    interests: ['yoga', 'ayurveda', 'wellness', 'backwaters'],
    description: 'A wellness-focused retreat in God\'s own country. Daily yoga, ayurvedic treatments, and peaceful backwater stays.',
    status: 'open',
    is_group_trip: true,
    created_at: '2024-12-01T10:00:00Z',
    updated_at: '2024-12-03T10:00:00Z',
    creator: mockProfiles[4],
  },
];

// Mock Matches
export const mockMatches: Match[] = [
  {
    id: 'match-1',
    trip_id: 'trip-1',
    user_id: 'demo-user',
    matched_user_id: '2',
    compatibility_score: 92,
    score_breakdown: {
      destination: 20,
      date_overlap: 18,
      interests: 17,
      travel_style: 15,
      safety_preference: 12,
      rating: 10,
    },
    status: 'pending',
    created_at: '2024-12-05T10:00:00Z',
    matched_user: mockProfiles[1],
    trip: mockTrips[0],
  },
  {
    id: 'match-2',
    trip_id: 'trip-3',
    user_id: 'demo-user',
    matched_user_id: '3',
    compatibility_score: 85,
    score_breakdown: {
      destination: 18,
      date_overlap: 16,
      interests: 15,
      travel_style: 14,
      safety_preference: 12,
      rating: 10,
    },
    status: 'pending',
    created_at: '2024-12-05T10:00:00Z',
    matched_user: mockProfiles[2],
    trip: mockTrips[2],
  },
  {
    id: 'match-3',
    trip_id: 'trip-4',
    user_id: 'demo-user',
    matched_user_id: '4',
    compatibility_score: 78,
    score_breakdown: {
      destination: 16,
      date_overlap: 14,
      interests: 14,
      travel_style: 12,
      safety_preference: 12,
      rating: 10,
    },
    status: 'pending',
    created_at: '2024-12-05T10:00:00Z',
    matched_user: mockProfiles[3],
    trip: mockTrips[3],
  },
];

// Mock Chat Rooms
export const mockChatRooms: ChatRoom[] = [
  {
    id: 'room-1',
    trip_id: 'trip-1',
    type: 'direct',
    created_at: '2024-12-05T10:00:00Z',
    participants: [
      { id: 'p1', room_id: 'room-1', user_id: 'demo-user', joined_at: '2024-12-05T10:00:00Z' },
      { id: 'p2', room_id: 'room-1', user_id: '2', joined_at: '2024-12-05T10:00:00Z', profile: mockProfiles[1] },
    ],
    last_message: {
      id: 'msg-1',
      room_id: 'room-1',
      sender_id: '2',
      content: 'Hey! Looking forward to the Ladakh trip!',
      message_type: 'text',
      is_read: false,
      created_at: '2024-12-05T14:30:00Z',
    },
  },
  {
    id: 'room-2',
    trip_id: 'trip-3',
    type: 'group',
    name: 'Rishikesh Gang',
    created_at: '2024-12-04T10:00:00Z',
    participants: [
      { id: 'p3', room_id: 'room-2', user_id: 'demo-user', joined_at: '2024-12-04T10:00:00Z' },
      { id: 'p4', room_id: 'room-2', user_id: '3', joined_at: '2024-12-04T10:00:00Z', profile: mockProfiles[2] },
      { id: 'p5', room_id: 'room-2', user_id: '1', joined_at: '2024-12-04T12:00:00Z', profile: mockProfiles[0] },
    ],
    last_message: {
      id: 'msg-2',
      room_id: 'room-2',
      sender_id: '3',
      content: 'Who is bringing the camping gear?',
      message_type: 'text',
      is_read: true,
      created_at: '2024-12-05T16:45:00Z',
    },
  },
];

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    room_id: 'room-1',
    sender_id: '2',
    content: 'Hey! I saw you are interested in the Ladakh trip. Welcome aboard!',
    message_type: 'text',
    is_read: true,
    created_at: '2024-12-05T10:00:00Z',
    sender: mockProfiles[1],
  },
  {
    id: 'msg-2',
    room_id: 'room-1',
    sender_id: 'demo-user',
    content: 'Thanks! I have been wanting to visit Ladakh for years. This seems perfect!',
    message_type: 'text',
    is_read: true,
    created_at: '2024-12-05T10:05:00Z',
  },
  {
    id: 'msg-3',
    room_id: 'room-1',
    sender_id: '2',
    content: 'Great! Do you have any experience with high altitude trekking?',
    message_type: 'text',
    is_read: true,
    created_at: '2024-12-05T10:10:00Z',
    sender: mockProfiles[1],
  },
  {
    id: 'msg-4',
    room_id: 'room-1',
    sender_id: 'demo-user',
    content: 'Yes, I did Triund last year and Valley of Flowers the year before.',
    message_type: 'text',
    is_read: true,
    created_at: '2024-12-05T10:15:00Z',
  },
  {
    id: 'msg-5',
    room_id: 'room-1',
    sender_id: '2',
    content: 'Perfect! Looking forward to the Ladakh trip!',
    message_type: 'text',
    is_read: false,
    created_at: '2024-12-05T14:30:00Z',
    sender: mockProfiles[1],
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'demo-user',
    type: 'match',
    title: 'New Match Found!',
    message: 'You have a 92% compatibility match for Ladakh Adventure trip',
    data: { trip_id: 'trip-1', match_id: 'match-1' },
    is_read: false,
    created_at: '2024-12-05T10:00:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'demo-user',
    type: 'message',
    title: 'New Message',
    message: 'Rahul Verma sent you a message',
    data: { room_id: 'room-1' },
    is_read: false,
    created_at: '2024-12-05T14:30:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'demo-user',
    type: 'trip_update',
    title: 'Trip Update',
    message: 'A new participant joined Rishikesh trip',
    data: { trip_id: 'trip-3' },
    is_read: true,
    created_at: '2024-12-04T12:00:00Z',
  },
];

// Mock Posts (Phase 3)
export const mockPosts: Post[] = [
  {
    id: 'post-1',
    user_id: '2',
    trip_id: 'trip-1',
    content: 'Just came back from the most incredible Ladakh trip! The Pangong Lake at sunrise was absolutely magical. 🏔️✨',
    post_type: 'post',
    media_urls: ['https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800'],
    location_name: 'Pangong Lake, Ladakh',
    location_coords: { lat: 33.7595, lng: 78.6662 },
    tags: ['ladakh', 'pangonglake', 'incredibleindia'],
    likes_count: 234,
    comments_count: 45,
    is_featured: true,
    created_at: '2024-11-20T10:00:00Z',
    author: mockProfiles[1],
  },
  {
    id: 'post-2',
    user_id: '1',
    content: 'Travel hack: Always carry a portable charger and a universal adapter. They have saved me countless times! 🔌',
    post_type: 'hack',
    media_urls: [],
    tags: ['travelhack', 'traveltips'],
    likes_count: 156,
    comments_count: 23,
    is_featured: false,
    created_at: '2024-11-18T10:00:00Z',
    author: mockProfiles[0],
  },
  {
    id: 'post-3',
    user_id: '3',
    trip_id: 'trip-3',
    content: 'River rafting in Rishikesh was INSANE! 16 km of pure adrenaline. Highly recommend for adventure lovers!',
    post_type: 'story',
    media_urls: ['https://images.unsplash.com/photo-1530866495561-507c9faab2ed?w=800'],
    location_name: 'Rishikesh, Uttarakhand',
    location_coords: { lat: 30.0869, lng: 78.2676 },
    tags: ['rishikesh', 'rafting', 'adventure'],
    likes_count: 189,
    comments_count: 34,
    is_featured: false,
    created_at: '2024-11-15T10:00:00Z',
    author: mockProfiles[2],
  },
];

// Mock Travel Recommendations (Phase 4)
export const mockRecommendations: TravelRecommendation[] = [
  {
    id: 'rec-1',
    destination: 'Leh-Ladakh',
    category: 'must_visit',
    name: 'Pangong Tso Lake',
    description: 'One of the world\'s highest saltwater lakes, famous for its changing colors.',
    image_url: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=400',
    rating: 4.9,
    tags: ['lake', 'photography', 'nature'],
  },
  {
    id: 'rec-2',
    destination: 'Goa',
    category: 'food',
    name: 'Fisherman\'s Wharf',
    description: 'Best seafood restaurant with waterfront dining experience.',
    image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400',
    rating: 4.5,
    price_range: '₹₹₹',
    tags: ['seafood', 'fine dining', 'romantic'],
  },
  {
    id: 'rec-3',
    destination: 'Rishikesh',
    category: 'activity',
    name: 'Bungee Jumping at Jumpin Heights',
    description: 'India\'s highest bungee jump at 83 meters!',
    image_url: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=400',
    rating: 4.7,
    price_range: '₹₹',
    tags: ['adventure', 'extreme sports', 'must try'],
  },
];

// Mock Community Boards (Phase 2)
export const mockCommunityBoards: CommunityBoard[] = [
  {
    id: 'board-1',
    name: 'Solo Female Travelers India',
    description: 'Safe space for women to share experiences and find travel buddies',
    cover_image: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=400',
    category: 'women',
    members_count: 5420,
    created_at: '2024-01-01T10:00:00Z',
  },
  {
    id: 'board-2',
    name: 'Budget Backpackers',
    description: 'Tips and tricks for traveling India on a shoestring budget',
    cover_image: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=400',
    category: 'budget',
    members_count: 8930,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'board-3',
    name: 'Mountain Lovers',
    description: 'For those who can\'t resist the call of the mountains',
    cover_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400',
    category: 'adventure',
    members_count: 12340,
    created_at: '2024-02-01T10:00:00Z',
  },
];

// Mock Local Guides (Phase 5)
export const mockLocalGuides: LocalGuide[] = [
  {
    id: 'guide-1',
    user_id: 'guide-user-1',
    destination: 'Leh-Ladakh',
    languages: ['English', 'Hindi', 'Ladakhi'],
    specialties: ['Trekking', 'Photography Tours', 'Monastery Visits'],
    hourly_rate: 1500,
    currency: 'INR',
    rating_avg: 4.9,
    total_bookings: 156,
    is_verified: true,
    profile: {
      id: 'guide-1',
      user_id: 'guide-user-1',
      full_name: 'Tenzin Dorje',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tenzin',
      bio: 'Born and raised in Ladakh. 15 years experience guiding tourists.',
      gender: 'male',
      interests: ['mountains', 'buddhism', 'local culture'],
      travel_style: ['adventure', 'cultural'],
      languages: ['English', 'Hindi', 'Ladakhi'],
      location: 'Leh, Ladakh',
      safety_badge: 'platinum',
      is_verified: true,
      is_premium: true,
      rating_avg: 4.9,
      total_trips: 156,
      trust_score: 99,
      kyc_status: 'approved',
      onboarding_complete: true,
      created_at: '2020-01-01T10:00:00Z',
      updated_at: '2024-12-01T10:00:00Z',
    },
  },
];

// Mock Insurance Plans (Phase 5)
export const mockInsurancePlans: InsurancePlan[] = [
  {
    id: 'ins-1',
    name: 'Basic Travel Guard',
    provider: 'ICICI Lombard',
    coverage_type: 'Domestic',
    price_per_day: 50,
    currency: 'INR',
    features: ['Medical Coverage up to 1L', 'Trip Cancellation', 'Lost Baggage'],
  },
  {
    id: 'ins-2',
    name: 'Adventure Plus',
    provider: 'Bajaj Allianz',
    coverage_type: 'Adventure',
    price_per_day: 150,
    currency: 'INR',
    features: ['Medical Coverage up to 5L', 'Adventure Sports', 'Emergency Evacuation', 'Trip Cancellation'],
  },
];

// Mock Partner Deals (Phase 5)
export const mockPartnerDeals: PartnerDeal[] = [
  {
    id: 'deal-1',
    partner_name: 'OYO Rooms',
    category: 'hotel',
    title: '20% Off on First Booking',
    description: 'Use code TRAVELMATE20 for exclusive discount',
    discount_percent: 20,
    promo_code: 'TRAVELMATE20',
    valid_until: '2025-03-31',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400',
  },
  {
    id: 'deal-2',
    partner_name: 'Decathlon',
    category: 'gear',
    title: 'Travel Gear Combo at 30% Off',
    description: 'Backpack + Trekking Shoes combo deal',
    discount_percent: 30,
    promo_code: 'TMGEAR30',
    valid_until: '2025-02-28',
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
  },
];

// Demo user profile
export const demoUserProfile: Profile = {
  id: 'demo-user',
  user_id: 'demo-user',
  full_name: 'Demo User',
  avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Demo',
  bio: 'Passionate traveler exploring India one destination at a time!',
  gender: 'prefer_not_to_say',
  date_of_birth: '1994-06-15',
  interests: ['hiking', 'photography', 'food', 'culture'],
  travel_style: ['adventure', 'cultural', 'backpacking'],
  languages: ['English', 'Hindi'],
  location: 'Mumbai, India',
  safety_badge: 'silver',
  is_verified: true,
  is_premium: false,
  rating_avg: 4.5,
  total_trips: 5,
  trust_score: 85,
  kyc_status: 'approved',
  onboarding_complete: true,
  created_at: '2024-06-01T10:00:00Z',
  updated_at: '2024-12-01T10:00:00Z',
};
